		window.sr = ScrollReveal();
		sr.reveal('.navbar', {duration:2000, origin:'top'});
		sr.reveal('.welcome-left', {duration:2500, origin:'left', distance:'400px'});
		sr.reveal('.welcome-right', {duration:2000, origin:'right', distance:'300px'});
		sr.reveal('.showcase-left', {duration:2000, origin:'top', distance:'300px'});
		sr.reveal('.showcase-right', {duration:2000, origin:'right', distance:'300px'});
		sr.reveal('.showcase-btn', {duration:2000, delay:500, origin:'bottom'});
		sr.reveal('#testimonial div', {duration:2000, origin:'bottom'});
		sr.reveal('.info-left', {duration:2000, origin:'left', distance:'300px', viewFactor:0.3});
		sr.reveal('.info-right', {duration:2000, origin:'right', distance:'300px', viewFactor:0.3});
		sr.reveal('.cert-header', {duration:2000, origin:'top', distance:'300px'});
		sr.reveal('.cert-left', {duration:2000, origin:'left', distance:'300px', viewFactor:0.3});
		sr.reveal('.cert-right', {duration:2000, origin:'right', distance:'300px', viewFactor:0.3});
		sr.reveal('.prof-header', {duration:2000, origin:'top', distance:'300px'});
		sr.reveal('.info-left-one', {duration:2000, origin:'left', distance:'300px', viewFactor:0.3});
		sr.reveal('.info-right-one', {duration:2000, origin:'right', distance:'300px', viewFactor:0.3});
		sr.reveal('.info-left-two', {duration:2000, origin:'left', distance:'300px', viewFactor:0.3});
		sr.reveal('.info-right-two', {duration:2000, origin:'right', distance:'300px', viewFactor:0.3});
		sr.reveal('.info-left-three', {duration:2000, origin:'left', distance:'300px', viewFactor:0.3});
		sr.reveal('.info-right-three', {duration:2000, origin:'right', distance:'300px', viewFactor:0.3});
		sr.reveal('.info-left-four', {duration:2000, origin:'left', distance:'300px', viewFactor:0.3});
		sr.reveal('.info-right-four', {duration:2000, origin:'right', distance:'300px', viewFactor:0.3});
		sr.reveal('#myCarousel', {duration:2000, origin:'bottom', distance:'300px', viewFactor:0.3});
		sr.reveal('.info-left-five', {duration:2000, origin:'left', distance:'300px', viewFactor:0.3});
		sr.reveal('.info-right-five', {duration:2000, origin:'right', distance:'300px', viewFactor:0.3});
		sr.reveal('.hobby-left', {duration:2000, origin:'left', distance:'300px', viewFactor:0.3});
		sr.reveal('.hobby-right', {duration:2000, origin:'right', distance:'300px', viewFactor:0.3});